### ISSUE TITLE
Improve the usability of `ibc-testkit` as a remote crate

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1269]
## Improvement Summary

Recently, it has been reported at #1257 that `ibc-testkit` in its current form is unusable at remote crate. I am listing the features that need to be added to allow `ibc-rs` users to leverage our testing framework easily.

## Proposal

- [ ] Remove the dependency of `AnyClientState` - remote crate may have a different `AnyClientState` implemented - possibly with their own light client.
- [ ] Remove the dependency of `MockStore` or `InMemoryStore` - remote crate may want to use their own storage for integration tests.
- [ ] Remove the dependency of `MockIbcStore` - remote crate may want to use their own implementation of `ValidationContext` and `ExecutionContext` for integration tests.

Let's use this issue to track the progress on this. We will probably come across more.
