### ISSUE TITLE
Release v0.54.0

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1304]
List of issues/PRs to address prior to v.0.54.0 release:

- [x] https://github.com/cosmos/ibc-rs/pull/1302
- [x] https://github.com/cosmos/ibc-rs/pull/1294
- [x] https://github.com/cosmos/ibc-rs/pull/1293
- [x] https://github.com/cosmos/ibc-rs/pull/1298
  - [x] The above PR will also address https://github.com/cosmos/ibc-rs/issues/1303
- [x] https://github.com/cosmos/ibc-rs/issues/1296
- [x] Dependency updates:
   - [x] prost
   - [x] tonic
   - [x] ics23
   - [x] ibc-proto-rs
   - [x] tendermint-rs
   - [x] rstest
- [x] Update basecoin-rs with the latest ibc-rs commit
- [ ] ~~Update `release.md` to reflect the addition of new `cosmwasm` workspace.~~
