### ISSUE TITLE
Tracking issue: `IbcEvent` is currently not compatible with ibc-go

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#137]
Events emitted by handlers are currently incompatible with ibc-go v5.0.0. This is a tracking issue:

- [x] Client events #144 
- [x] Connection events #145 
- [x] Channel events #146

____

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
