### ISSUE TITLE
Tracking issue: Remove "crossing hellos" logic from connection and channel handshakes

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#143]
Was removed from the protocol; see corresponding [ibc-go issue](https://github.com/cosmos/ibc/issues/628).

- [x] #156 
- [x] #157
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
Make sure to remove [this](https://github.com/cosmos/ibc-rs/blob/1f94dbdc8b5ebbc7f92f6f088ba0c79f9738c588/crates/ibc/src/lib.rs#L9) `#![allow(deprecated)]` before closing.
