### ISSUE TITLE
Implement (parts of) ibc-go/ADR006

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc-rs#173]
## Summary

This is a tracking issue for the Q1 objective of _"Implementing of relevant parts of [ADR006 (AKA 02-client-refactor)](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-006-02-client-refactor.md)"_ 
(_See https://github.com/cosmos/ibc-go/pull/1871 for more context_)

### Acceptance Criteria
- [x] ~~merging header/misbehaviour interface and renaming to ClientMessage~~
- [ ] https://github.com/cosmos/ibc-rs/issues/404
- [ ] https://github.com/cosmos/ibc-rs/issues/530
- [ ] https://github.com/cosmos/ibc-rs/issues/535
- [ ] setting client/consensus states within the light client instead of at the 02-client level
- [ ] emission of upgraded consensus state
- [ ] We should add a check that incoming header's `trusted_validators` matches the `next_validators_hash` that was persisted in the trusted consensus state (copied from https://github.com/cosmos/ibc-rs/issues/22 as this wasn't addressed in #22 and depends on 02-client-refactor changes)
    - Equivalent check in ibc-go is here: https://github.com/cosmos/ibc-go/blob/147e0f1954ede691bb977ff185b9d0500ec4bd0a/modules/light-clients/07-tendermint/types/update.go#L152
    - The check is significant b/c the header's `trusted_validator_set` is used in the trusted block state in `verify`: https://github.com/informalsystems/ibc-rs/blob/b44ade9f88c7faf4d0b6f9e672dbef08d2ab3817/modules/src/clients/ics07_tendermint/client_def.rs#L98
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
We must add fix the misbehaviour execute handler to not perform full verification. (see https://github.com/cosmos/ibc-rs/pull/290#pullrequestreview-1214171067)

**Comment by Farhad-Shabani** [comment]
Looks like we've resolved items of this issue. @plafer, could you also check?

**Comment by plafer** [comment]
Yup!

**Comment by plafer** [comment]
Yup!
