### ISSUE TITLE
Enable Nomic and Namada to get to mainnet

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#431]
## Background

This issue aims to track the work going into the Q1 objective of enabling Nomic and Namada to reach Mainnet by incorporating the IBC-rs module. 
It is worth noting that achieving this objective also results in achieving “_supporting Anoma's onboarding efforts_” goal and is mainly coupled with "[ADR005](https://github.com/cosmos/ibc-rs/blob/main/docs/architecture/adr-005-handlers-redesign.md)", which can be followed under the "ActivityGroup" field in the IBC-rs project board.

## Task List

```[tasklist]
### Implement ADR005
- [X] Implement the `ValidationContext`/`ExecutionContext` API separation (ADR-005) to ensure compatibility with Namada’s requirements
```

```[tasklist]
### Reflect ADR-005 changes on all other impacted parts/modules
- [x] https://github.com/cosmos/ibc-rs/issues/415
- [x] https://github.com/cosmos/ibc-rs/pull/442
```

```[tasklist]
### Reach out to Nomic, Namada, and Penumbra and provide assistance with the implementation
- [x] Discuss some recent design changes (during v0.28.0 & v0.29.0) with Namada and Penumbra 
- [x] Anoma decided to try this change for the pre-launch (Feb 21, 2022)
```

```[tasklist]
### Update existing unit and integration tests to cover ADR-005
- [x] https://github.com/informalsystems/basecoin-rs/issues/73
- [x] https://github.com/cosmos/ibc-rs/issues/413
- [x] https://github.com/cosmos/ibc-rs/issues/440
- [x] https://github.com/informalsystems/basecoin-rs/issues/77
```

```[tasklist]
### Fix potential findings and bugs
- [x] https://github.com/cosmos/ibc-rs/issues/550
- [x] https://github.com/cosmos/ibc-rs/issues/563
```

```[tasklist]
### Obtain feedback and implement new design requirements
- [x] https://github.com/cosmos/ibc-rs/issues/480
- [x] https://github.com/cosmos/ibc-rs/issues/482
- [x] https://github.com/cosmos/ibc-rs/issues/486
- [x] https://github.com/cosmos/ibc-rs/issues/490
- [x] https://github.com/cosmos/ibc-rs/issues/502
```
