### ISSUE TITLE
Assist non-cosmos chains in adopting IBC (Q2 2023)

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#608]
## Background

This issue is in continuation of #431 and tracks progress towards one of the Q2 objectives “**Assisting non-cosmos chains in adopting IBC and applying feedback”** with the expected following results:

1. Finish Anoma’s onboarding and reduce their open issues to zero 
2. Ensure prompt resolution of findings from our key customers including CompFi, Namada, Nomic, and Penumbra

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/535
- [ ] https://github.com/cosmos/ibc-rs/issues/628
- [ ] https://github.com/cosmos/ibc-rs/issues/640
- [ ] https://github.com/cosmos/ibc-rs/issues/684
- [ ] https://github.com/cosmos/ibc-rs/issues/695
```
