### ISSUE TITLE
[ICS02] Implement IBC client recovery mechanisms

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#738]
## Problem Statement

If a client gets frozen or expired it can no longer be updated, the associated connection(s) and channel(s) will also stop working and funds in the channels will be permanently locked and not transferrable.

ibc-rs needs a mechanism by which frozen IBC clients can be recovered. This functionality has been implemented in ibc-go as part of [ADR 026](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-026-ibc-client-recovery-mechanisms.md). We'll need to implement similar functionality in ibc-rs in order to maintain feature parity.
```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/1112
- [ ] https://github.com/cosmos/ibc-rs/issues/1110
- [ ] https://github.com/cosmos/ibc-rs/issues/1111
- [ ] https://github.com/informalsystems/basecoin-rs/issues/173
```

**Comment by rnbguy** [comment]
All the tasks are finished. Does that make this tracking issue finished too?

**Comment by Farhad-Shabani** [comment]
I think @seanchen1991 is addressing the final aspect of this feature in https://github.com/informalsystems/basecoin-rs/issues/173 to ensure its functionality. Once that's completed, we can consider closing this issue.

**Comment by rnbguy** [comment]
@seanchen1991 we can close this now, right?
