### ISSUE TITLE
Develop the first iteration of IBC-rs website

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#743]
## Background

As part of our ongoing effort to enhance IBC-rs usability, we aim to build a documentation portal that functions as a central hub for both our users: those who want to learn more about IBC-rs and developers who wish to use, integrate, or upgrade `ibc-rs` on their respective chains.

Before the official launch of the website, the following tasks should be accomplished within a dedicated feature branch:

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/808
- [ ] https://github.com/cosmos/ibc-rs/issues/809
- [ ] https://github.com/cosmos/ibc-rs/issues/810
- [ ] https://github.com/cosmos/ibc-rs/issues/811
- [ ] https://github.com/cosmos/ibc-rs/issues/812
- [ ] https://github.com/informalsystems/hermes/issues/3507
- [ ] https://github.com/cosmos/ibc-rs/issues/813
- [ ] https://github.com/cosmos/ibc-rs/issues/814
```

The first iteration of content preparation aims for adequate documentation, though it may lack in detail. Improvements will follow in subsequent iterations. Also, the below sections may be added after the launch:

- https://github.com/cosmos/ibc-rs/issues/815
- https://github.com/cosmos/ibc-rs/issues/816

**Comment by DaviRain-Su** [comment]
I recommendate this https://docusaurus.io/ .
