### ISSUE TITLE
Assist users in adopting IBC-rs (Q3 2023)

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#807]
## Background

This issue is a continuation of #608 and pertains to one of our objectives for 2023-Q3, which is to “**assist users in adopting IBC-rs**”. The primary intent here is to track and ensure the timely resolution of day-to-day maintenance tasks, address feature requests, and promptly fix bugs reported by our users as follows:

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/821
- [ ] https://github.com/cosmos/ibc-rs/issues/792
- [ ] https://github.com/cosmos/ibc-rs/pull/772
- [ ] https://github.com/cosmos/ibc-rs/issues/764
- [ ] https://github.com/cosmos/ibc-rs/issues/763
- [ ] https://github.com/cosmos/ibc-rs/issues/761
- [ ] https://github.com/cosmos/ibc-rs/issues/752
- [ ] https://github.com/cosmos/ibc-rs/issues/741
```
