### ISSUE TITLE
Support first iteration of integrating ibc-rs into Sovereign SDK chains

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#861]
## Background

This issue tracks efforts toward the integration of `ibc-rs` into the Sovereign SDK chains during Q3 2023.
The initial step involves implementing `ibc-rs` interfaces and introducing essential modifications required to operate the ICS20 application, allowing token transfers between Comet-driven and Sovereign SDK chains.

The implementation is currently in progress here: [informalsystems/sovereign-sdk](https://github.com/informalsystems/sovereign-sdk/tree/plafer/ibc-integration) 

```[tasklist]
### Tasks on `sovereign-sdk`
- [ ] https://github.com/informalsystems/sovereign-sdk/pull/1
- [ ] https://github.com/informalsystems/sovereign-sdk/pull/2
- [ ] https://github.com/informalsystems/sovereign-sdk/pull/4
- [ ] https://github.com/informalsystems/sovereign-sdk/pull/5
- [ ] https://github.com/informalsystems/sovereign-sdk/pull/11
```

```[tasklist]
### Tasks on `ibc-rs` originated because of this integration
- [ ] https://github.com/cosmos/ibc-rs/issues/837
- [ ] https://github.com/cosmos/ibc-rs/issues/839
- [ ] https://github.com/cosmos/ibc-rs/pull/845
- [ ] https://github.com/cosmos/ibc-rs/pull/846
- [ ] https://github.com/cosmos/ibc-rs/pull/847
- [ ] https://github.com/cosmos/ibc-rs/pull/856
- [ ] https://github.com/cosmos/ibc-rs/issues/857
- [ ] https://github.com/cosmos/ibc-rs/issues/859
```
