### ISSUE TITLE
Continue assisting users in adopting ibc-rs (Q4 2023)

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#882]
This issue is an extension of https://github.com/cosmos/ibc-rs/issues/807. It is concerned with overarching the objective of "**Continue support diverse range of blockchains in adopting ibc-rs**" set for Q4 2023. We here track day-to-day maintenance tasks, minor feature requests, and bugs reported by our users:

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/850
- [ ] https://github.com/cosmos/ibc-rs/pull/894
- [ ] https://github.com/cosmos/ibc-rs/issues/911
- [ ] https://github.com/cosmos/ibc-rs/pull/938
- [ ] https://github.com/cosmos/ibc-rs/pull/939
- [ ] https://github.com/cosmos/ibc-rs/pull/940
- [ ] https://github.com/cosmos/ibc-rs/pull/958
- [ ] https://github.com/cosmos/ibc-rs/issues/961
- [ ] https://github.com/cosmos/ibc-rs/issues/970
- [ ] https://github.com/cosmos/ibc-rs/issues/978
- [ ] https://github.com/cosmos/ibc-rs/issues/987
- [ ] https://github.com/cosmos/ibc-rs/pull/992
- [ ] https://github.com/cosmos/ibc-rs/pull/1004
- [ ] https://github.com/cosmos/ibc-rs/pull/1005
- [ ] https://github.com/cosmos/ibc-rs/pull/1008
- [ ] https://github.com/cosmos/ibc-rs/pull/1010
- [ ] https://github.com/cosmos/ibc-rs/pull/1015
- [ ] https://github.com/cosmos/ibc-rs/pull/1017
```
