### ISSUE TITLE
Ensure adequate support and tests for Sovereign SDK integration

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#883]
## Background

In continuation of #861, this issue serves to track our advancements in achieving the goal of "Ensuring adequate support and tests for Sovereign SDK integration" during Q4 2023. This activity primarily entails the resolution of remaining implementation details related to `ibc-rs`, along with conducting essential tests to assess the functionality of IBC core and token transfer application.
Furthermore, we will also be working on investigating and implementing an on-chain Sovereign light client to be deployed on Cosmos chains and facilitate bidirectional communication for this IBC integration.

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-rs/issues/861
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/2
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/4
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/5
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/6
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/7
```

**Comment by Farhad-Shabani** [comment]
The objective of this issue accomplishment and all the necessary features have been incorporated into ibc-rs through various issues/PRs since Q3 2023.
